[package]
name = "rust_subtitle_filter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = "0.27.2"
encoding_rs = "0.8.34"
regex = "1.10.4"
rfd = "0.14.1"
